import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400','500','600','800'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased ${roboto.className} bg-[#F4EEDB]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
